name: 🐛 Bug Report
description: File a bug report here
title: "[Bug]: "
labels: ["bug"]
assignees: ["KirioXX", "LawaGolem"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! 🤗
        Please make sure this topic hasn't been already submitted by someone by looking through other open/closed issues. 😃

  - type: textarea
    id: bug-description
    attributes:
      label: Description of the bug
      description: Give us a brief description of what happened and what should have happened.
      placeholder: |
        Tell us what you see!
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true
      
  - type: textarea
    id: expected-behaviour
    attributes:
      label: Expected behaviour
      description: |
        A clear and concise description of what you expected to happen.
        
  - type: textarea
    id: evidance
    attributes:
      label: Screenshots & Videos
      description: |
        If applicable, add screenshots to help explain your problem.
        
  - type: textarea
    id: devices
    attributes:
      label: Device(s) affected
      description: Tell use the devices where you have found this issue.
      placeholder: |
        Desktop:
        OS: [e.g. iOS]
        Browser [e.g. chrome, safari]
        Browser Version [e.g. 22]
        Phone / tablet:

        Device: [e.g. iPhone6]
        OS: [e.g. iOS8.1]
        App or Browser? [e.g. Tusks app, Chrome, Safari]
        App or Browser Version [e.g. 22]
        App or Browser Build [e.g. 503]
    validations:
      required: true

  - type: textarea
    id: additional-information
    attributes:
      label: Additional Information
      description: |
        Provide any additional information such as logs, screenshots, likes, scenarios in which the bug occurs so that it facilitates resolving the issue.
