name: ✨ New Feature Pitch
description: Write a new feature pitch.
title: "[Feature Pitch]: "
labels: ["pitch"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## Main Information

  - type: dropdown
    attributes:
      multiple: false
      label: Type of Feature
      description: Select the type of feature request.
      options:
        - "✨ New Feature"
        - "📝 Documentation"
        - "🎨 Style and UI"
        - "🔨 Code Refactor"
        - "⚡ Performance Improvements"
        - "✅ New Test"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Give us a brief description of the feature or enhancement you would like
    validations:
      required: true

  - type: checkboxes
    id: areas-of-concern
    attributes:
      label: Areas of Concern
      description: Which areas will be affected by this change?
      options:
        - label: Watchtower
        - label: App
        - label: Emails
        - label: Dashboards/Reports
        - label: PDF Exports
        - label: Andons
  
  - type: textarea
    id: documents
    attributes:
      label: Documents
      description: Add additional documents. (e.g miro links, google doc links)
      placeholder: |
        * [Miro: Name](https://miro.com)
        * [Google Doc](https://google.com)
        * [Equals](https://go.equals.com)

  - type: input
    id: deadline
    attributes:
      label: Deadline - Ship date 🗓️
      description: "When's this due to ship? (e.g. '1st May 2023' or 'End of May')"

  - type: markdown
    attributes:
      value: |
        ---
        ## Additional Information
        
  - type: textarea
    id: rabbit-holes
    attributes:
      label: Potential Rabbit Holes ⚠️
      description: Where might we get stuck or burn lots of time?

  - type: textarea
    id: no-gos
    attributes:
      label: No-go's ⛔
      description: What should we keep away from?

  - type: textarea
    id: risks
    attributes:
      label: Risks 🤔
      description: Where could things go off track?
      
  - type: textarea
    id: scope-hammer
    attributes:
      label: Scope hammer candidates 🔨
      description: What might we choose to exclude?
