name: ✨ Feature Request
description: Suggest an idea for this project
title: "[Feature]: "
labels: ["enhancement"]
assignees: ["KirioXX", "LavaGolem"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request! 🤗
        Please make sure this feature request hasn't been already submitted by someone by looking through other open/closed issues. 😃

  - type: dropdown
    attributes:
      multiple: false
      label: Type of Feature
      description: Select the type of feature request.
      options:
        - "✨ New Feature"
        - "📝 Documentation"
        - "🎨 Style and UI"
        - "🔨 Code Refactor"
        - "⚡ Performance Improvements"
        - "✅ New Test"
    validations:
      required: true
      
  - type: textarea
    id: job-to-be-done
    attributes:
      label: Job To Be Done
      description: What is the job that a user would like to be fulfilled with this feature.
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Give us a brief description of the feature or enhancement you would like
    validations:
      required: true

  - type: textarea
    id: rabbit-holes
    attributes:
      label: Potential Rabbit Holes ⚠️

  - type: textarea
    id: no-gos
    attributes:
      label: No-go's ⛔

  - type: textarea
    id: risks
    attributes:
      label: Risks 🤔
      
  - type: textarea
    id: scope-hammer
    attributes:
      label: Scope hammer candidates 🔨

  - type: textarea
    id: deadline
    attributes:
      label: Deadline - Ship date 🗓️

  - type: textarea
    id: additional-information
    attributes:
      label: Additional Information
      description: Give us some additional information on the feature request like proposed solutions, links, screenshots, etc.
