name: ✨ Feature Request
description: Suggest an idea for this project
title: "[Feature]: "
labels: ["enhancement"]
assignees: ["KirioXX", "LavaGolem"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request! 🤗
        Please make sure this feature request hasn't been already submitted by someone by looking through other open/closed issues. 😃

  - type: dropdown
    attributes:
      multiple: false
      label: Type of Feature
      description: Select the type of feature request.
      options:
        - "✨ New Feature"
        - "📝 Documentation"
        - "🎨 Style and UI"
        - "🔨 Code Refactor"
        - "⚡ Performance Improvements"
        - "✅ New Test"
    validations:
      required: true
      
  - type: textarea
    id: job-to-be-done
    attributes:
      label: Job To Be Done
      description: |
          What is the job that a user would like to be fulfilled with this feature. 
          [Jobs To Be Done: Definition, Examples, and Framework for Your Business](https://www.coursera.org/articles/jobs-to-be-done)
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Give us a brief description of the feature or enhancement you would like
    validations:
      required: true

  - type: textarea
    id: rabbit-holes
    attributes:
      label: Potential Rabbit Holes ⚠️
      description: Where might we get stuck or burn lots of time?

  - type: textarea
    id: no-gos
    attributes:
      label: No-go's ⛔
      description: What should we keep away from?

  - type: textarea
    id: risks
    attributes:
      label: Risks 🤔
      description: Where could things go off track?
      
  - type: textarea
    id: scope-hammer
    attributes:
      label: Scope hammer candidates 🔨
      description: What might we choose to exclude?

  - type: input
    id: deadline
    attributes:
      label: Deadline - Ship date 🗓️
      description: When's this due to ship? (e.g. "1st May 2023" or "End of May")

  - type: textarea
    id: additional-information
    attributes:
      label: Additional Information
      description: Give us some additional information on the feature request like proposed solutions, links, screenshots, etc.
